# Generated by Django 5.0.1 on 2024-01-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('vid', models.IntegerField(primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='venuepics')),
                ('state', models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Rajasthan', 'Rajasthan'), ('Kerala', 'Kerala')], max_length=50)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
    ]
