# Generated by Django 5.0.1 on 2024-01-31 17:05

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='venue',
            managers=[
                ('prod', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventApp.venue')),
            ],
        ),
    ]
